Addition of Attacks/Reports
coinspect/wallet-security-verification-standard pull request #4
Opened 2024-01-17 14:56 UTC by mabdullah22

I have added attacks/reports column and added some reports. This can be expanded further and more reports/attacks can be added.

2024-01-29 12:19 UTC, matiassequeira requested changes
Hello @mabdullah22, thank you for your valuable input and congrats on your reports. Once you add the new column I'll merge your PR

2024-01-29 12:19 UTC, matiassequeira commented on README.md
> +|  #  | Description
Can you add the attacks/reports column to section #5? I've a report related to 5.2

2024-01-29 18:24 UTC, mabdullah22 commented
I have added it. Cheers :)

2024-03-25 15:58 UTC, matiassequeira approved these changes
lgtm

2024-03-25 15:59 UTC, merged